### ISSUE TITLE
Retire this project

### ISSUE THREAD

**Issue by tschm** [tschm/token-mint-action#70]
Installation via twine with a username/token combination is just too fragile.
I am using 

```yaml
name: Bump version and publish

on:
  workflow_dispatch

jobs:
  tag:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        uses: cvxgrp/.github/actions/uv/tag@v2.0.13
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: tag
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: read
      # This permission is required for trusted publishing.
      id-token: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```
